### ISSUE TITLE
Nie działa logowanie

### ISSUE THREAD

**Issue by grakucki** [grakucki/ITechSite#2]
Przy nacid fklsd fms f
sdsd d
![jellyfish](https://cloud.githubusercontent.com/assets/12529713/8426420/e3dc11dc-1f0f-11e5-9cda-e55e56245eef.jpg)

**Comment by grakucki** [comment]
ale dokładnie o co chodzi

**Comment by mrozent** [comment]
Widziałem

**Comment by pawelpolakowski** [comment]
ja też widziałem

**Comment by pawelpolakowski** [comment]
Zmieniłem awatar

**Comment by grakucki** [comment]
Czyli zorwiązany problem. Dziękuję z owocną współpracę;)
