### ISSUE TITLE
Dodanie do autostartu aplikacji

### ISSUE THREAD

**Issue by pawelpolakowski** [grakucki/ITechSite#3]
Można dodać podczas procesu instalacyjnego krok, w którym aplikacja dopisuje się sama do autostartu dla usera operator.
Nie trzeba będzie pamiętać o ręcznym dodawaniu za każdym razem przy instalowaniu nowego komputera na stanowisku

**Comment by grakucki** [comment]
Wykonano dodanie aplikacji do autostartu użytkownika. Aplikacja wykonuje to sama po pierwszym uruchomieniu oraz kolejnych update'ach

**Comment by pawelpolakowski** [comment]
ok. Przyjęte do wiadomości.

**Comment by grakucki** [comment]
Sprawdziłeś czy działa?

**Comment by pawelpolakowski** [comment]
Po aktualizacji aplikacji w autostarcie pojawia się wpis z nowym linkiem.
Autostart działa
