### ISSUE TITLE
walidacja pola DateTime

### ISSUE THREAD

**Issue by mrozent** [grakucki/ITechSite#5]
Przy dodawaniu dokumentów podpowiadana jest wartość aktualna dla pól DateTime zawierająca datę i czas. Walidacja domaga się tylko daty.
To istotne do usunięcia bo chcemy żeby zaczęli wprowadzać dokumenty

**Comment by grakucki** [comment]
Sprawdziłem i jedynie co trzeba zrobić to wstawić plik i kliknąć utwórz. Nie wyskakuje walidacja

**Comment by mrozent** [comment]
potwierdzam, jest OK
