### ISSUE TITLE
zamieszanie w rozszerzeniach

### ISSUE THREAD

**Issue by mrozent** [grakucki/ITechSite#7]
!! Raczej niski priorytet !!
Przy edycji dokumentów można pomieszać rozszerzenia i potem jest kłopot przy podglądzie - zawartość pliku nie zgadza się z rozszerzeniem

![zrzut - edycja dokumentow](https://cloud.githubusercontent.com/assets/13115188/8459301/7ff4b47c-201c-11e5-8b60-fab67d828ddb.png)

**Comment by grakucki** [comment]
U mnie nie ma problemu z walidacją daty może poprawiłem ją wcześniej
Zmiana rozszerzenia nie jest na teraz bo to trzeba zrobić java script w przeglądarce. I należny rozpatrzeć co to znaczy że zmienia się nazwa pliku?

**Comment by mrozent** [comment]
O coś takiego chodziło. OK
